### PR TITLE
Make field accept optional placeholder

### PR DESCRIPTION
**Pull request by manogi**
This PR lets the field accept an optional placeholder passed with the addMeta method which will be shown instead of `add Tags...` - for example if you are actually dealing with "categories" instead of tags.

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
Tests are still failing here. I fixed them on the main branch, so perhaps you should rebase

**Comment by manogi** [comment]
Hmm... I did merge the current main into the branch before re-PRing. The tests fail when they try to download the nova repo:
CleanShot 2021-07-02 at 13 22 53@2x

**Comment by manogi** [comment]
Someone wrote something about the package repo being down an hour ago:
CleanShot 2021-07-02 at 13 25 04@2x

**Comment by manogi** [comment]
The regular tests pass locally:
CleanShot 2021-07-02 at 13 28 09@2x

**Comment by Nielsvanpach** [comment]
Ok, thanks!

**Pull request merged**
