### PR TITLE
add custom model support

### PR DESCRIPTION
**Pull request by chrisrenga**
uses the model specified in the underlying spatie/laravel-tags package config file

### CODE REVIEW

**Comment by chrisrenga** [comment]
@freekmurze seems like the tests are failing on a few Spatie nova packages due to an auth error while trying to download Nova. Eg. [test on spatie/nova-translatable](https://github.com/spatie/nova-translatable/pull/55/checks?check_run_id=1551698713 )

might be that the Nova composer GitHub secret needs to be updated?

**Comment by freekmurze** [comment]
I'll take care of the tests soon.

Could you document the new functionality in the readme? I'll merge after that.

**Comment by archangel2080** [comment]
Hey @freekmurze any luck on getting the tests fixed?

**Comment by freekmurze** [comment]
Didn't find that time for that yet...

**Pull request closed without merging**
